cargo-features = ["profile-overrides"]

[workspace]
members = [
  "lalr1-core",
  "ll1-core",
  "grammar-config",
  "parser-gen",
  "parser-macros",
  "tests",
]

[profile.dev.overrides."*"]
opt-level = 3