[package]
name = "lalr1-core"
version = "0.1.0"
authors = ["MashPlant <740678788@qq.com>"]
edition = "2018"

[dependencies]
smallvec = "0.6.9"
grammar-config = { path = "../grammar-config" }
bitset = { git = "https://github.com/MashPlant/bitset" }