[package]
name = "parser-gen"
version = "0.1.0"
authors = ["MashPlant <740678788@qq.com>"]
edition = "2018"

[dependencies]
re2dfa = { git = "https://github.com/MashPlant/re2dfa" }
aho-corasick = "0.7"
lalr1-core = { path = "../lalr1-core" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "lalr1gen"
path = "src/lalr1.rs"

[[bin]]
name = "ll1gen"
path = "src/ll1.rs"