on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build rust
        run: |
          rustup default nightly
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wasm-pack build
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: cd www && npm install && npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@2.0.2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: frontend
          BRANCH: gh-pages
          FOLDER: www/dist